#!/bin/sh

dir=/data
module=image
host=10.28.6.154

/usr/local/bin/inotifywait -mrq --timefmt '%d/%m/%y %H:%M' --format '%T %w%f %e' \
 --event CLOSE_WRITE,create,move,delete $dir | while read date time file event
 do
  echo $event'-'$file
  case $event in
   (MODIFY|CREATE|MOVE|MODIFY,ISDIR|CREATE,ISDIR|MODIFY,ISDIR)
    
     cmd="rsync -avzt --progress --password-file=/usr/local/rsync/server.pas --exclude='*' --include=$file $dir $host::$module"
     echo $cmd
     $cmd
    

   #(MOVED_FROM|MOVED_FROM,ISDIR|DELETE|DELETE,ISDIR)
    
   #	cmd="rsync -avzt --delete-excluded --progress --password-file=/usr/local/rsync/server.pas --exclude="$file" $dir $host::$module"
   #	echo $cmd
   #	$cmd
    
  esac
 done &
